---
- name: Install centos-release-scl-rh (CentOS only)
  package:
    name: centos-release-scl-rh
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Enables SCL (RHEL only)
  command: "yum-config-manager --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms"
  become: true
  when: ansible_distribution == 'RedHat'

- name: Install required software for vsts-agent
  yum:
    name:
      - icu
      - libunwind
      - git
      - python-pip
    state: installed
  become: true
  tags:
    - pkg

- name: Pip install pexpect (we need a new-enough version that isn't packaged in redhat 7.x
  pip:
    name: pexpect
    state: present
  tags:
    - pkg
    - pexpect

- name: Include configure vsts-agent tasks
  include_tasks: configure_vsts_agent.yml
  when: dryrun is not defined
  tags:
    - config

- name: Install systemd service file
  template:
    src: vsts-agent.service.j2
    dest: /etc/systemd/system/vsts-agent.service
    mode: "0755"
  become: true

- name: Enable and start vsts-agent service
  systemd:
    name: vsts-agent
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
  when: dryrun is not defined
  tags:
    - service
