---
- name: Install centos-release-scl-rh (CentOS only)
  package:
    name: centos-release-scl
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Enables SCL (RHEL only)
  command: "yum-config-manager --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms"
  become: true
  when: ansible_distribution == 'RedHat'

- name: Install required software for vsts-agent
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - icu
    - libunwind
    - rh-git29
    - python2-pip
  become: true
  when:
    - not ansible_check_mode
  tags:
    - pkg

- name: Pip install pexpect (we need a new-enough version that isn't packaged in redhat 7.x
  pip:
    name: "{{item}}"
    state: present
    extra_args: -i https://pypi.python.org/simple
  with_items:
    - pexpect
  when:
    - not ansible_check_mode
  tags:
    - pkg
    - pexpect

- name: Include configure vsts-agent tasks
  include_tasks: configure_vsts_agent.yml
  when:
    - not ansible_check_mode
    - dryrun is not defined
  tags:
    - config

- name: Initial installation of systemd service files and generation of runsvc.sh
  command: "./svc.sh install {{vsts_agent_user}}"
  args:
    chdir: "{{vsts_agentfolder}}"
    creates: "/etc/systemd/system/vsts.agent.{{ vsts_accountname }}.{{ vsts_agent_name }}.service"
  become: true
  when:
    - not ansible_check_mode
    - dryrun is not defined
  tags:
    - config
    - service

- name: Enable and start vsts-agent service
  service:
    name: "vsts.agent.{{ vsts_accountname }}.{{ vsts_agent_name }}"
    enabled: yes
    state: started
  become: true
  when:
    - not ansible_check_mode
    - dryrun is not defined
  tags:
    - service
